// Code generated by "stringer -type=AnnotationType -trimprefix=AnnotationType"; DO NOT EDIT.

package processor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnnotationTypeAPI-0]
	_ = x[AnnotationTypeVersion-1]
	_ = x[AnnotationTypeServer-2]
	_ = x[AnnotationTypeVariable-3]
	_ = x[AnnotationTypeTag-4]
	_ = x[AnnotationTypeSecurity-5]
	_ = x[AnnotationTypeSecurityAPIKey-6]
	_ = x[AnnotationTypeSecurityHTTP-7]
	_ = x[AnnotationTypeOperation-8]
	_ = x[AnnotationTypeParameter-9]
	_ = x[AnnotationTypeRequestBody-10]
	_ = x[AnnotationTypeResponse-11]
	_ = x[AnnotationTypeJSONSchema-12]
	_ = x[AnnotationTypeJSONExample-13]
	_ = x[AnnotationTypeCallback-14]
	_ = x[AnnotationTypeMaximum-15]
}

const _AnnotationType_name = "APIVersionServerVariableTagSecuritySecurityAPIKeySecurityHTTPOperationParameterRequestBodyResponseJSONSchemaJSONExampleCallbackMaximum"

var _AnnotationType_index = [...]uint8{0, 3, 10, 16, 24, 27, 35, 49, 61, 70, 79, 90, 98, 108, 119, 127, 134}

func (i AnnotationType) String() string {
	if i < 0 || i >= AnnotationType(len(_AnnotationType_index)-1) {
		return "AnnotationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnnotationType_name[_AnnotationType_index[i]:_AnnotationType_index[i+1]]
}
